// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP vclTest_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(rcpp_hello_world());
    return __result;
END_RCPP
}
// test
void test();
RcppExport SEXP vclTest_test() {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    test();
    return R_NilValue;
END_RCPP
}
// test_double
void test_double();
RcppExport SEXP vclTest_test_double() {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    test_double();
    return R_NilValue;
END_RCPP
}
