# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call('vclTest_rcpp_hello_world', PACKAGE = 'vclTest')
}

#' @export
test <- function() {
    invisible(.Call('vclTest_test', PACKAGE = 'vclTest'))
}

#' @export
test_double <- function() {
    invisible(.Call('vclTest_test_double', PACKAGE = 'vclTest'))
}

